# Generated by Django 4.0.1 on 2022-02-26 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scomment', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='subcomments',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subcomment', to='home.sub_comments'),
            preserve_default=False,
        ),
    ]
