# Generated by Django 4.0.1 on 2022-02-26 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sub_comments_comments_subcomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scomment', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='subcomments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomment', to='home.sub_comment'),
        ),
        migrations.DeleteModel(
            name='sub_comments',
        ),
    ]
