# Generated by Django 4.0.1 on 2023-04-21 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_comments_subcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='man',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL), max_length=255),
        ),
    ]
