# Generated by Django 4.0.1 on 2023-05-05 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Image/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
