# Generated by Django 4.0.1 on 2023-05-07 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_add_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='primary_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
